'use client';
import { useMemo, useState } from 'react';

type Room={id:string;name:string};
type Property={id:string;name:string;rooms:Room[]};

const categories=[
  ['Air Conditioner','❄️','مكيف'],['Refrigerator','🧊','ثلاجة'],['Washer','🧺','غسالة'],['Water Heater','♨️','سخان'],
  ['Water Pump','💧','مضخة'],['Water Tank','🚰','خزان'],['Water Filter','🫗','فلتر'],['CCTV','📷','كاميرات'],['Other','⌂','أخرى']
] as const;

const styles=`.wizard{max-width:980px}.wizardHead{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding-bottom:18px;border-bottom:1px solid #edf1ee}.wizardHead h2{margin:5px 0 0}.stepPills{display:flex;align-items:center;gap:8px;direction:ltr}.stepPills span{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#edf2ee;color:#75837b;font-weight:800}.stepPills span.on{background:#0f6a48;color:#fff}.stepPills i{display:block;width:28px;height:2px;background:#dce5df}.wizardStep{padding-top:22px}.wizardStep>label,.formGrid label{display:block;font-size:13px;font-weight:800;color:#405248;margin-bottom:6px}.wizardStep>select,.formGrid input,.formGrid select{width:100%;padding:13px 14px;border:1px solid #d9e3dc;border-radius:14px;background:#fbfdfb;margin-bottom:16px;outline:none}.wizardStep>select:focus,.formGrid input:focus,.formGrid select:focus{border-color:#72b593;box-shadow:0 0 0 4px rgba(15,106,72,.08);background:#fff}.categoryGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:18px 0}.categoryChoice{border:1px solid #dde6df;background:#fbfdfb;border-radius:18px;padding:18px;cursor:pointer;display:grid;gap:7px;place-items:center;color:#33473d}.categoryChoice b{font-size:28px}.categoryChoice span{font-weight:800}.categoryChoice.selected{background:#eaf5ee;border-color:#84bfa1;box-shadow:0 0 0 3px rgba(15,106,72,.06);color:#12583f}.wizardActions{display:flex;justify-content:space-between;gap:10px;margin-top:18px}.formGrid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.wizardSummary{display:flex;align-items:center;justify-content:space-between;padding:13px 15px;background:#eef6f1;border-radius:14px;color:#52655b}.wizardSummary strong{color:#15583f}.assetGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.assetCard{display:grid;gap:16px}.assetCardTop{display:flex;justify-content:space-between;align-items:flex-start}.assetIcon{width:50px;height:50px;border-radius:17px;background:#edf5f0;display:grid;place-items:center;font-size:25px}.assetCard h3{margin:0 0 5px}.assetFacts{display:grid;grid-template-columns:1fr 1fr;gap:10px}.assetFacts div{padding:11px;border-radius:14px;background:#f6f9f6}.assetFacts small{display:block;color:#748179;margin-bottom:4px}.assetFacts strong{font-size:13px}@media(max-width:900px){.assetGrid{grid-template-columns:1fr 1fr}}@media(max-width:640px){.wizardHead{align-items:center}.wizardHead .eyebrow{display:none}.wizardHead h2{font-size:20px}.categoryGrid{grid-template-columns:repeat(2,1fr)}.formGrid,.assetGrid{grid-template-columns:1fr}.wizardActions .btn{flex:1}}`;

export function AssetWizard({properties}:{properties:Property[]}){
  const [step,setStep]=useState(1);
  const [propertyId,setPropertyId]=useState(properties[0]?.id||'');
  const [category,setCategory]=useState('Air Conditioner');
  const rooms=useMemo(()=>properties.find(p=>p.id===propertyId)?.rooms||[],[properties,propertyId]);
  if(!properties.length)return <div className="empty"><div style={{fontSize:36}}>🏠</div><h3>أضف منزلًا أولًا</h3><p className="muted">بعد إضافة المنزل يمكنك بناء سجل أجهزته وصيانته وضماناته.</p></div>;
  return <><style>{styles}</style><div className="card wizard">
    <div className="wizardHead"><div><span className="eyebrow">إضافة أصل جديد</span><h2>عرّف BaytiCare على جهازك</h2></div><div className="stepPills"><span className={step>=1?'on':''}>1</span><i></i><span className={step>=2?'on':''}>2</span><i></i><span className={step>=3?'on':''}>3</span></div></div>
    <form action="/api/assets" method="post">
      <input type="hidden" name="category" value={category}/>
      {step===1&&<div className="wizardStep"><h3>أين يوجد الجهاز؟</h3><p className="muted">اختر المنزل والغرفة حتى نبني النسخة الرقمية بشكل منظم.</p><label>المنزل</label><select name="propertyId" value={propertyId} onChange={e=>setPropertyId(e.target.value)} required>{properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><label>الغرفة / الموقع</label><select name="roomId" defaultValue=""><option value="">غير محدد الآن</option>{rooms.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select><button type="button" className="btn" onClick={()=>setStep(2)}>التالي ←</button></div>}
      {step===2&&<div className="wizardStep"><h3>ما نوع الجهاز؟</h3><p className="muted">اختر الفئة الآن. التعرف التلقائي من الصورة سيكون مسار AI مستقل حتى لا نحفظ معلومات غير مؤكدة.</p><div className="categoryGrid">{categories.map(([value,icon,label])=><button type="button" key={value} className={'categoryChoice '+(category===value?'selected':'')} onClick={()=>setCategory(value)}><b>{icon}</b><span>{label}</span></button>)}</div><div className="wizardActions"><button type="button" className="btn ghost" onClick={()=>setStep(1)}>رجوع</button><button type="button" className="btn" onClick={()=>setStep(3)}>التالي ←</button></div></div>}
      {step===3&&<div className="wizardStep"><h3>تفاصيل الجهاز والصيانة</h3><p className="muted">أدخل ما تعرفه فقط. يمكنك إكمال الناقص لاحقًا.</p><div className="formGrid"><div><label>اسم الجهاز</label><input name="name" placeholder="مثال: مكيف الصالة" required/></div><div><label>الشركة المصنعة</label><input name="manufacturer" placeholder="Carrier / LG / Samsung"/></div><div><label>الموديل</label><input name="model" placeholder="رقم الموديل"/></div><div><label>الرقم التسلسلي</label><input name="serialNumber" placeholder="Serial Number"/></div><div><label>تاريخ الشراء</label><input name="purchaseDate" type="date"/></div><div><label>سعر الشراء</label><input name="purchasePrice" type="number" step="0.01" placeholder="ر.س"/></div><div><label>انتهاء الضمان</label><input name="warrantyExpiresAt" type="date"/></div><div><label>دورية الصيانة</label><select name="maintenanceIntervalDays" defaultValue="180"><option value="90">كل 3 أشهر</option><option value="180">كل 6 أشهر</option><option value="365">كل سنة</option></select></div></div><div className="wizardSummary"><span>الفئة المختارة</span><strong>{categories.find(x=>x[0]===category)?.[2]}</strong></div><div className="wizardActions"><button type="button" className="btn ghost" onClick={()=>setStep(2)}>رجوع</button><button className="btn" type="submit">✓ حفظ وإنشاء خطة الصيانة</button></div></div>}
    </form>
  </div></>
}
