'use client';
import { useMemo, useState } from 'react';

type Room={id:string;name:string};
type Property={id:string;name:string;rooms:Room[]};
type ScanResult={category?:string;manufacturer?:string;model?:string;serialNumber?:string;confidence:number;mode?:string;error?:string};

const categories=[['Air Conditioner','❄️','مكيف'],['Refrigerator','🧊','ثلاجة'],['Washer','🧺','غسالة'],['Water Heater','♨️','سخان'],['Water Pump','💧','مضخة'],['Water Tank','🚰','خزان'],['Water Filter','🫗','فلتر'],['CCTV','📷','كاميرات'],['Other','⌂','أخرى']] as const;
const styles=`.wizard{max-width:980px}.wizardHead{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding-bottom:18px;border-bottom:1px solid #edf1ee}.wizardHead h2{margin:5px 0 0}.stepPills{display:flex;align-items:center;gap:8px;direction:ltr}.stepPills span{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#edf2ee;color:#75837b;font-weight:800}.stepPills span.on{background:#0f6a48;color:#fff}.stepPills i{display:block;width:28px;height:2px;background:#dce5df}.wizardStep{padding-top:22px}.wizardStep>label,.formGrid label{display:block;font-size:13px;font-weight:800;color:#405248;margin-bottom:6px}.wizardStep>select,.formGrid input,.formGrid select{width:100%;padding:13px 14px;border:1px solid #d9e3dc;border-radius:14px;background:#fbfdfb;margin-bottom:16px;outline:none}.wizardStep>select:focus,.formGrid input:focus,.formGrid select:focus{border-color:#72b593;box-shadow:0 0 0 4px rgba(15,106,72,.08);background:#fff}.categoryGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:18px 0}.categoryChoice{border:1px solid #dde6df;background:#fbfdfb;border-radius:18px;padding:18px;cursor:pointer;display:grid;gap:7px;place-items:center;color:#33473d}.categoryChoice b{font-size:28px}.categoryChoice span{font-weight:800}.categoryChoice.selected{background:#eaf5ee;border-color:#84bfa1;box-shadow:0 0 0 3px rgba(15,106,72,.06);color:#12583f}.wizardActions{display:flex;justify-content:space-between;gap:10px;margin-top:18px}.formGrid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.wizardSummary{display:flex;align-items:center;justify-content:space-between;padding:13px 15px;background:#eef6f1;border-radius:14px;color:#52655b}.wizardSummary strong{color:#15583f}.scanDrop{position:relative;display:grid!important;place-items:center;text-align:center;border:1.5px dashed #9dc5ae!important;border-radius:20px;padding:22px!important;background:#f5fbf7;cursor:pointer;margin:12px 0 16px!important}.scanDrop input{position:absolute;inset:0;opacity:0;cursor:pointer}.scanDrop .scanIcon{font-size:32px;margin-bottom:7px}.scanDrop strong{color:#164f3b}.scanDrop small{color:#77857d;margin-top:5px}.scanNotice{padding:11px 13px;border-radius:12px;margin:8px 0}.scanNotice.error{background:#fff0f0;color:#a73636}.scanResult{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:13px 15px;border-radius:15px;background:#edf7f1;margin-bottom:14px}.scanResult p{margin:0;font-size:13px;color:#52655b}.scanResult>div{display:flex;align-items:center;gap:9px;white-space:nowrap}@media(max-width:640px){.wizardHead{align-items:center}.categoryGrid{grid-template-columns:repeat(2,1fr)}.formGrid{grid-template-columns:1fr}.wizardActions .btn{flex:1}.scanResult{align-items:flex-start;flex-direction:column}}`;

export function AssetWizard({properties}:{properties:Property[]}){
 const [step,setStep]=useState(1); const [propertyId,setPropertyId]=useState(properties[0]?.id||''); const [roomId,setRoomId]=useState('');
 const [category,setCategory]=useState('Air Conditioner'); const [manufacturer,setManufacturer]=useState(''); const [model,setModel]=useState(''); const [serialNumber,setSerialNumber]=useState(''); const [scan,setScan]=useState<ScanResult|null>(null); const [scanning,setScanning]=useState(false); const [scanError,setScanError]=useState('');
 const rooms=useMemo(()=>properties.find(p=>p.id===propertyId)?.rooms||[],[properties,propertyId]);
 function changeProperty(id:string){setPropertyId(id);setRoomId('');}
 async function analyze(file?:File){if(!file)return;setScanning(true);setScanError('');setScan(null);try{const fd=new FormData();fd.set('file',file);const res=await fetch('/api/ai/scan-asset',{method:'POST',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||'تعذر التحليل');setScan(data);if(data.category&&categories.some(x=>x[0]===data.category))setCategory(data.category);if(data.manufacturer)setManufacturer(data.manufacturer);if(data.model)setModel(data.model);if(data.serialNumber)setSerialNumber(data.serialNumber);}catch(e){setScanError(e instanceof Error?e.message:'تعذر تحليل الصورة');}finally{setScanning(false);}}
 if(!properties.length)return <div className="empty"><div style={{fontSize:36}}>🏠</div><h3>أضف منزلًا أولًا</h3><p className="muted">بعد إضافة المنزل يمكنك بناء سجل أجهزته وصيانته وضماناته.</p></div>;
 return <><style>{styles}</style><div className="card wizard"><div className="wizardHead"><div><span className="eyebrow">إضافة أصل جديد</span><h2>عرّف BaytiCare على جهازك</h2></div><div className="stepPills"><span className={step>=1?'on':''}>1</span><i/><span className={step>=2?'on':''}>2</span><i/><span className={step>=3?'on':''}>3</span></div></div>
 <form action="/api/assets" method="post"><input type="hidden" name="propertyId" value={propertyId}/><input type="hidden" name="roomId" value={roomId}/><input type="hidden" name="category" value={category}/>
 {step===1&&<div className="wizardStep"><h3>أين يوجد الجهاز؟</h3><p className="muted">اختر المنزل والغرفة حتى نبني النسخة الرقمية بشكل منظم.</p><label>المنزل</label><select value={propertyId} onChange={e=>changeProperty(e.target.value)} required>{properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><label>الغرفة / الموقع</label><select value={roomId} onChange={e=>setRoomId(e.target.value)}><option value="">غير محدد الآن</option>{rooms.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select><button type="button" className="btn" onClick={()=>setStep(2)}>التالي ←</button></div>}
 {step===2&&<div className="wizardStep"><h3>صوّر الجهاز أو اختر نوعه</h3><p className="muted">صوّر واجهة الجهاز أو ملصق البيانات. BaytiCare سيقرأ النوع والشركة والموديل والرقم التسلسلي عندما يكون ظاهرًا.</p><label className="scanDrop"><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>analyze(e.target.files?.[0])}/><span className="scanIcon">📸</span><strong>{scanning?'جاري تحليل الصورة...':'التقط صورة أو اختر من الجهاز'}</strong><small>JPG / PNG / WEBP · حتى 8MB</small></label>{scanError&&<div className="scanNotice error">{scanError}</div>}{scan&&<div className="scanResult"><div><span className="badge">{scan.mode==='ai'?'AI Vision':'وضع تجريبي'}</span><strong>{Math.round((scan.confidence||0)*100)}% ثقة</strong></div><p>{scan.mode==='ai'?'تمت قراءة الصورة. راجع البيانات قبل الحفظ.':'واجهة المسح جاهزة، لكن مزود AI غير مفعّل في الإنتاج بعد.'}</p></div>}<div className="categoryGrid">{categories.map(([value,icon,label])=><button type="button" key={value} className={'categoryChoice '+(category===value?'selected':'')} onClick={()=>setCategory(value)}><b>{icon}</b><span>{label}</span></button>)}</div><div className="wizardActions"><button type="button" className="btn ghost" onClick={()=>setStep(1)}>رجوع</button><button type="button" className="btn" onClick={()=>setStep(3)}>راجع البيانات ←</button></div></div>}
 {step===3&&<div className="wizardStep"><h3>راجع بيانات الجهاز والصيانة</h3><p className="muted">البيانات المستخرجة لا تُحفظ تلقائيًا؛ عدّل أي معلومة قبل التأكيد.</p><div className="formGrid"><div><label>اسم الجهاز</label><input name="name" placeholder="مثال: مكيف الصالة" required/></div><div><label>الشركة المصنعة</label><input name="manufacturer" value={manufacturer} onChange={e=>setManufacturer(e.target.value)} placeholder="Carrier / LG / Samsung"/></div><div><label>الموديل</label><input name="model" value={model} onChange={e=>setModel(e.target.value)} placeholder="رقم الموديل"/></div><div><label>الرقم التسلسلي</label><input name="serialNumber" value={serialNumber} onChange={e=>setSerialNumber(e.target.value)} placeholder="Serial Number"/></div><div><label>تاريخ الشراء</label><input name="purchaseDate" type="date"/></div><div><label>سعر الشراء</label><input name="purchasePrice" type="number" step="0.01" placeholder="ر.س"/></div><div><label>انتهاء الضمان</label><input name="warrantyExpiresAt" type="date"/></div><div><label>دورية الصيانة</label><select name="maintenanceIntervalDays" defaultValue="180"><option value="90">كل 3 أشهر</option><option value="180">كل 6 أشهر</option><option value="365">كل سنة</option></select></div></div><div className="wizardSummary"><span>الفئة المختارة</span><strong>{categories.find(x=>x[0]===category)?.[2]}</strong></div><div className="wizardActions"><button type="button" className="btn ghost" onClick={()=>setStep(2)}>رجوع</button><button className="btn" type="submit">✓ حفظ وإنشاء خطة الصيانة</button></div></div>}
 </form></div></>;
}
